# Generated by Django 4.2 on 2023-04-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loja", "0002_item_quantidade_item_valor"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrinho_item",
            name="quantidade",
            field=models.IntegerField(default=1),
        ),
    ]
