# Generated by Django 4.2 on 2023-04-28 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loja", "0003_carrinho_item_quantidade"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carrinho_item",
            options={"verbose_name_plural": "Carrinho_Itens"},
        ),
    ]
