# Generated by Django 4.2 on 2023-04-28 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loja", "0004_alter_carrinho_item_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carrinho_item",
            name="item",
        ),
    ]
