# Generated by Django 4.2 on 2023-04-28 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("loja", "0005_remove_carrinho_item_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carrinho",
            name="itens",
        ),
        migrations.RemoveField(
            model_name="item",
            name="nome",
        ),
        migrations.AddField(
            model_name="carrinho",
            name="nome_carrinho",
            field=models.CharField(default="Carrinho_1", max_length=255),
        ),
        migrations.AddField(
            model_name="carrinho_item",
            name="item",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="loja.item"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="nome_item",
            field=models.CharField(default="", max_length=255),
        ),
    ]
