# Generated by Django 4.2 on 2023-04-28 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loja", "0006_remove_carrinho_itens_remove_item_nome_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carrinho_item",
            name="carrinho",
        ),
        migrations.DeleteModel(
            name="Carrinho",
        ),
    ]
