# Generated by Django 4.2 on 2023-04-29 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("loja", "0007_remove_carrinho_item_carrinho_delete_carrinho"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="foto",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="uploader.image",
            ),
        ),
    ]
